server:
  port: 8081
spring:
  application:
    name: weixin
  thymeleaf:
    cache: false
    enabled: false
  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .jsp
  # 这里设置要指向的路径，多个使用英文逗号隔开,默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  activemq:
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
    packages:
      trust-all: true

queueName: publish.queue
topicName: publish.topic